### PR TITLE
Add support for relative snapshots

### PR DESCRIPTION
**Pull request by stuartlong**
## Description
Adds some configuration options to the register call to allow consumers to specify a different name for snapshots and to store snapshots next to their tests instead of in the base directory.

### Example
cypress.json
```js
{
  snapshotFileName: 'cypress-snapshots.js',
  useRelativeSnapshots: true
}
```

### Removing NSP
Also removes the `nsp check` pre-push hook as nsp has been deprecated: https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting?_ga=2.86111704.173770583.1554322814-927454317.1554322814

It was also causing the push to fail on my Windows machine.

### CODE REVIEW

**Comment by stuartlong** [comment]
@bahmutov , would you mind removing?

**Comment by Kaltsoon** [comment]
Big thanks to @stuartlong for this feature! Is there any estimate when or whether this feature is released? I find the current way of storing all the snapshots into a single file very inconvenient.

**Comment by bahmutov** [comment]
yeah I need to update release token to publish new version to NPM, hopefully will do today

**Pull request merged**
